### ISSUE TITLE
Replace NullTraceSpanProvider with NoopTraceSpanProvider

### ISSUE THREAD

**Issue by StephenCleary** [Faithlife/FaithlifeTracing#13]
Currently, our `NullTraceSpanProvider` will return `null`. In an ASP.NET application, this is only observed when *not* running locally or in a test environment (i.e., in production). Consumers "just have to know" that there can be a `null` `ITraceSpan`, and use null propagation everywhere tracing is done. In addition, to catch any missing null propagation, all this tracing must be tested explicitly in scenarios where a `NullTraceSpanProvider` is injected (and again, consumers "just have to know" and remember this).

If we replaced `NullTraceSpanProvider` with a true `NoopTraceSpanProvider`, then any missing null-propagation expressions would just become no-ops.

Possible implementation:

```C#
public sealed class NoopTraceSpanProvider : ITraceSpanProvider
{
	public static ITraceSpanProvider Instance { get; } = new NoopTraceSpanProvider();

	ITraceSpan ITraceSpanProvider.CurrentSpan => NoopTraceSpan.NoopTraceSpanInstance;

	private sealed class NoopTraceSpan : ITraceSpan
	{
		public static ITraceSpan NoopTraceSpanInstance { get; } = new NoopTraceSpan();

		public ITracer Tracer => NoopTracer.NoopTracerInstance;

		public string TraceId => string.Empty;

		public string SpanId => string.Empty;

		public ITraceSpan CurrentSpan => this;

		public void Dispose() { }

		public void SetTag(string name, string value) { }
	}

	private sealed class NoopTracer : ITracer
	{
		public static ITracer NoopTracerInstance { get; } = new NoopTracer();

		public ITraceSpan ExtractSpan(Func<string, string> extractKey) => NoopTraceSpan.NoopTraceSpanInstance;

		public void InjectSpan(ITraceSpan traceSpan, Action<string, string> inject) { }

		public ITraceSpan StartSpan(ITraceSpan parent, TraceSpanKind kind, IEnumerable<(string Name, string Value)> tags) => NoopTraceSpan.NoopTraceSpanInstance;
	}
}
```

**Comment by bgrainger** [comment]
:+1:

The intention of `span.StartChildSpan(TraceSpanKind.Client, new[] { ... })` (which internally uses the null-conditional member access operator) where `span` could be `null` was to skip the allocation of the array of tags in the 99.9% of requests that aren't being traced. 

However, an easier-to-use and easier-to-get-right API is better than an API optimised for maximum possible performance when this is likely to be the smallest source of allocations in our services.
