### ISSUE TITLE
Add no-op trace provider

### ISSUE THREAD

**Issue by ejball** [Faithlife/FaithlifeTracing#2]
When tracing is disabled, it would be nice to have a standard no-op `ITraceProvider` implementation that returns `null` for `CurrentTrace`.

**Comment by ianfisk** [comment]
@ejball I would like to add this if you haven't started. As far as I can tell, [here](https://github.com/Faithlife/FaithlifeTracing/blob/772e2ff96e9d6c43d8642f9cad95887442ae2cc5/src/Faithlife.Tracing.AspNet/AspNetTracing.cs#L61) is the only place we set the `ITraceProvider` on the `HttpContext.Current`. My plan would be to ensure `HttpContext.Current.Items[c_providerKey]` is always set to a non-`null` provider before `BeginRequest` returns.

EDIT: I realized that we want a no-op `ITraceProvider` so registering this in the type registry won't throw an exception if tracing is disabled. I wonder if setting this provider in `BeginRequest` is too late, and instead we should merely return the no-op provider in [`GetProvider`](https://github.com/Faithlife/FaithlifeTracing/blob/01e2748fcc257ad7686fdb5c7922cdf7f87f36f0/src/Faithlife.Tracing.AspNet/AspNetTracing.cs#L75-L76).

**Comment by ejball** [comment]
Feel free! cc @bgrainger

**Comment by bgrainger** [comment]
> I wonder if setting this provider in BeginRequest is too late, and instead we should merely return the no-op provider in GetProvider.

Yes, this is the better approach.

I suggest creating a `NullTraceProvider` class and changing `GetProvider` to return `(current logic) ?? NullTraceProvider.Instance`.

**Comment by ianfisk** [comment]
That’s exactly what I was thinking.
