### ISSUE TITLE
Rename ITrace to ISpan

### ISSUE THREAD

**Issue by ddunkin** [Faithlife/FaithlifeTracing#8]
The interface that represents a span is named `ITrace`, but a trace is a graph of spans. Getting the terminology straight was hard enough when I was first looking at OpenTracing; we shouldn't make it harder by not using the most obvious names.

**Comment by bgrainger** [comment]
I feel like @ejball had the exact same concern when reviewing #1, but I had some rationalisation at the time.

It would probably be better to adopt the standard terminology of https://github.com/opentracing/specification/blob/master/specification.md#the-opentracing-data-model.

**Comment by ddunkin** [comment]
https://github.com/w3c/distributed-tracing and https://opencensus.io/core-concepts/tracing/ also use the same terms.

**Comment by bgrainger** [comment]
`Span` might possibly be confusing/conflicting with `Span<T>`.

I think an earlier version of #1 had `TraceSpan` but it was considered too verbose.

But `ITrace` is confusing given the standard nomenclature and `<see cref="ITrace"/> represents a span in a trace` is probably an admission of defeat.

**Comment by ejball** [comment]
If we are sufficiently concerned, I'd certainly prefer `TraceSpan` to `Span`.

**Comment by ddunkin** [comment]
`TraceSpan` works for me.
